### ISSUE TITLE
Error! Cannot read property 'title' of undefined

### ISSUE THREAD

**Issue by blackyzero** [DeuxHuitHuit/algolia-webcrawler#20] opened 2017-05-10 04:28 UTC
Dear all,

I tried to execute the angolia-webcrawler, but getting the following error, no new info updated, it's only work with first time of execution.

```
root@fb1f88228516:/opt/angolia/algolia-webcrawler# algolia-webcrawler --config config.json
Welcome to "press.biofruit.com" algolia-webcrawler v1.1.0

Configuring your index BIOFruitPressIndex
Sitemap https://press.biofruit.com/sitemap.xml do not contains any urls
Parsing Sitemap https://press.biofruit.com/sitemap-posts.xml
Registered https://press.biofruit.com/eco-bio-organic-products-and-how-to-distinguish-them/
Registered https://press.biofruit.com/usda-organic-and-non-gmo-verified-seal/
Registered https://press.biofruit.com/5-tips-for-becoming-usda-certified-organic/
Registered https://press.biofruit.com/usda-certified-organic/
Registered https://press.biofruit.com/globalg-a-p-certification/
Registered https://press.biofruit.com/bio-siegel-a-national-german-organic-standard/
Sitemap https://press.biofruit.com/sitemap-posts.xml registered 6 / 6 urls
Configured index properly

Error! Cannot read property 'title' of undefined
Error! Cannot read property 'title' of undefined
Error! Cannot read property 'title' of undefined
Error! Cannot read property 'title' of undefined
Error! Cannot read property 'title' of undefined
Error! Cannot read property 'title' of undefined

Removing old entries...
Deleting old entries done.
root@fb1f88228516:/opt/angolia/algolia-webcrawler#
```
Could you please advise how to fix it?
Thanks a lot.

**Comment by franklouwers** [comment] 2017-05-10 13:37
This is a regression in 1.1.0 it seems. I had the same issue, and this was fixed by downgrading to 1.0.2

**Comment by nitriques** [comment] 2017-05-10 14:34
Yup it's a regression I need to fix. Temporary fix: add [those four keys](https://github.com/DeuxHuitHuit/algolia-webcrawler/blob/master/config.json#L28-L39) in your config

**Comment by nitriques** [comment] 2017-05-10 14:35
Actually this is a duplicate of #19

**Comment by nitriques** [comment] 2017-05-12 02:22
Version `1.1.1` + signed release are up! Thanks for playing!

**Closed** 2017-05-12 02:21 UTC
Labels: bug, duplicate, help wanted

**Comment by blackyzero** [comment] 2017-05-23 03:11
great! thanks @nitriques
